apiVersion: coreos.com/v1
kind: AppVersion
metadata:
  name: tectonic-etcd
  namespace: tectonic-system
  labels:
    managed-by-channel-operator: "true"
spec:
  #TODO: use an env variable like other appversions. See assets.tf
  desiredVersion: 0.0.1
  paused: false
status:
  currentVersion: 0.0.1
  paused: false
